import { Product } from './types';

export const sampleProducts: Product[] = [
  {
    id: "1",
    title: "TableTrack - The Complete SaaS Restaurant Management System",
    author: { name: "ajay138", category: "PHP Scripts" },
    price: 29,
    rating: 4.5,
    reviews: 10,
    sales: 123,
    lastUpdated: "28 Nov 24",
    software: { version: "PHP 8.x", framework: "Laravel" },
    fileTypes: ["JavaScript JS", "JavaScript JSON", "HTML", "CSS", "Sass", "PHP"],
    thumbnail: "https://kzmk5g7qxu247irkg9x4.lite.vusercontent.net/placeholder.svg?height=400&width=600",
  },
  {
    id: "2",
    title: "SmartInvoice - Simplified Billing System",
    author: { name: "johnDoe", category: "PHP Scripts" },
    price: 25,
    rating: 4.0,
    reviews: 8,
    sales: 98,
    lastUpdated: "27 Nov 24",
    software: { version: "PHP 7.x", framework: "CodeIgniter" },
    fileTypes: ["HTML", "CSS", "PHP"],
    thumbnail: "https://kzmk5g7qxu247irkg9x4.lite.vusercontent.net/placeholder.svg?height=400&width=600",
  },
  {
    id: "3",
    title: "EZStore - Multi-vendor E-Commerce System",
    author: { name: "sarahTech", category: "JavaScript Apps" },
    price: 39,
    rating: 4.7,
    reviews: 15,
    sales: 143,
    lastUpdated: "28 Nov 24",
    software: { version: "PHP 8.x", framework: "Laravel" },
    fileTypes: ["JavaScript JS", "JSON", "HTML", "CSS"],
    thumbnail: "https://kzmk5g7qxu247irkg9x4.lite.vusercontent.net/placeholder.svg?height=400&width=600",
  },
  {
    id: "4",
    title: "ProTasker - Task Management System",
    author: { name: "devPro", category: "PHP Scripts" },
    price: 30,
    rating: 4.3,
    reviews: 12,
    sales: 115,
    lastUpdated: "26 Nov 24",
    software: { version: "PHP 8.x", framework: "CodeIgniter" },
    fileTypes: ["PHP", "HTML", "CSS"],
    thumbnail: "https://kzmk5g7qxu247irkg9x4.lite.vusercontent.net/placeholder.svg?height=400&width=600",
  },
  // Add 25 more items here with unique properties.
  {
    id: "29",
    title: "AdWizard - Ad Campaign Manager",
    author: { name: "adMaster", category: "JavaScript Apps" },
    price: 35,
    rating: 4.6,
    reviews: 22,
    sales: 170,
    lastUpdated: "25 Nov 24",
    software: { version: "PHP 7.x", framework: "Laravel" },
    fileTypes: ["JavaScript JS", "HTML", "CSS", "Sass", "JSON"],
    thumbnail: "https://kzmk5g7qxu247irkg9x4.lite.vusercontent.net/placeholder.svg?height=400&width=600",
  },
];
